//import 'package:flutter/material.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
//export 'package:ventas_carprog/widgets/product_card.dart';
export 'package:ventas_carprog/widgets/product_image.dart';
export 'package:ventas_carprog/screens/home_screen.dart';
export 'package:ventas_carprog/screens/clientes_screen.dart';
export 'package:ventas_carprog/screens/ventas_screen.dart';
export 'package:ventas_carprog/screens/alert_screen.dart';
export 'package:ventas_carprog/screens/productlist_screen.dart';
export 'package:ventas_carprog/screens/product_screen.dart';
export 'package:ventas_carprog/screens/loading_screen.dart';
// export 'package:cloud_firestore/cloud_firestore.dart';
// export 'package:firebase_core/firebase_core.dart';
